/* ===== わーくす（GitHub: sachi-saiwai / t0rixs） ===== */
const WORKS = [
  {
    name: "katatsumuri",
    url: "https://github.com/sachi-saiwai/katatsumuri",
    desc: "ブラウザで動くドット絵エディタ。",
    tech: ["React", "JavaScript", "HTML/CSS"],
  },
  {
    name: "nietzsche",
    url: "https://github.com/sachi-saiwai/nietzsche",
    desc: "JavaScriptで作ったWebアプリ。",
    tech: ["React", "JavaScript", "HTML/CSS"],
  },
  {
    name: "sushior",
    url: "https://github.com/sachi-saiwai/sushior",
    desc: "Flutterで作ったクロスプラットフォームアプリ。",
    tech: ["Flutter", "Dart"],
  },
  {
    name: "portfoliogogogo",
    url: "https://github.com/sachi-saiwai/portfoliogogogo",
    desc: "Flutter製のポートフォリオアプリ。",
    tech: ["Flutter", "Dart"],
  },
  {
    name: "pocketreception",
    url: "https://github.com/t0rixs/PocketReception",
    desc: "Flutterで共同開発した図書業務DX化アプリ。",
    tech: ["Flutter", "Dart"],
  },
];

/* ===== すきなおんがく [曲名, アーティスト] ===== */
const MUSIC = [
  ["ロックンロールは鳴り止まないっ", "神聖かまってちゃん"],
  ["夜中の風船MarkⅡ", "NEE"],
  ["第一次世界", "NEE"],
  ["コンティニュー", "NEE"],
  ["不幸前夜", "NEE"],
  ["一袋", "NEE"],
  ["海と花束", "きのこ帝国"],
  ["クロノスタシス", "きのこ帝国"],
  ["everything is my guitar", "andymori"],
  ["CITY LIGHTS", "andymori"],
  ["都会を走る猫", "andymori"],
  ["クレイジークレーマー", "andymori"],
  ["Peace", "andymori"],
  ["16", "andymori"],
  ["1984", "andymori"],
  ["モンゴロイドブルース", "andymori"],
  ["誰にも見つけられない星になれたら", "andymori"],
  ["サンセットクルージング", "andymori"],
  ["ハッピーエンド", "andymori"],
  ["ベンガルトラとウィスキー", "andymori"],
  ["クラシック", "JUDY AND MARY"],
  ["そばかす", "JUDY AND MARY"],
  ["motto", "JUDY AND MARY"],
  ["くじら12号", "JUDY AND MARY"],
  ["Over Drive", "JUDY AND MARY"],
  ["リピドー", "銀杏BOYS"],
  ["夢で逢えたら", "銀杏BOYS"],
  ["error", "FACT"],
  ["in the blink of an eye", "FACT"],
  ["a fact of life", "FACT"],
  ["ape", "FACT"],
  ["disclosure", "FACT"],
  ["slip of the lip", "FACT"],
  ["why...", "FACT"],
  ["ジターバグ", "ELLEGARDEN"],
  ["The Autumn Song", "ELLEGARDEN"],
  ["チーズケーキ・ファクトリー", "ELLEGARDEN"],
  ["高架線", "ELLEGARDEN"],
  ["Stereoman", "ELLEGARDEN"],
  ["Addicted", "ELLEGARDEN"],
  ["Breathing", "ELLEGARDEN"],
  ["Make a wish", "ELLEGARDEN"],
  ["Mr.feather", "ELLEGARDEN"],
  ["金星", "ELLEGARDEN"],
  ["風の日", "ELLEGARDEN"],
  ["Red Hot", "ELLEGARDEN"],
  ["My favorite Song", "ELLEGARDEN"],
  ["Alternative Plans", "ELLEGARDEN"],
  ["Strawberry Margarita", "ELLEGARDEN"],
  ["No.13", "ELLEGARDEN"],
  ["Marry me", "ELLEGARDEN"],
  ["missing", "ELLEGARDEN"],
  ["supernova", "04 Limited Sazabys"],
  ["スターフィッシュ", "04 Limited Sazabys"],
  ["swim", "04 Limited Sazabys"],
  ["monolith", "04 Limited Sazabys"],
  ["Squall", "04 Limited Sazabys"],
  ["アフターターク", "ASIAN KUNG-FU GENERATION"],
  ["ソラニン", "ASIAN KUNG-FU GENERATION"],
  ["ムスタング", "ASIAN KUNG-FU GENERATION"],
  ["アンダースタンド", "ASIAN KUNG-FU GENERATION"],
  ["24時", "ASIAN KUNG-FU GENERATION"],
];

/* ===== すきなほん [タイトル, 著者] ===== */
const BOOKS = [
  ["ガールズ・アット・ジ・エッジ", "犬怪寅日子"],
  ["コンビニ人間", "村田沙耶香"],
  ["消滅世界", "村田沙耶香"],
  ["世界99", "村田沙耶香"],
  ["信仰", "村田沙耶香"],
  ["変半身", "村田沙耶香"],
  ["殺人出産", "村田沙耶香"],
  ["丸の内魔法少女ミラクリーナ", "村田沙耶香"],
  ["しろいろの街の、その骨の体温の", "村田沙耶香"],
  ["告白", "湊かなえ"],
  ["少女", "湊かなえ"],
  ["未来", "湊かなえ"],
  ["贖罪", "湊かなえ"],
  ["落日", "湊かなえ"],
  ["カケラ", "湊かなえ"],
  ["人間標本", "湊かなえ"],
  ["夜行観覧車", "湊かなえ"],
  ["ポイズンドーターホーリーマザー", "湊かなえ"],
  ["火花", "又吉直樹"],
  ["人間", "又吉直樹"],
  ["星へ落ちる", "金原ひとみ"],
  ["蛇にピアス", "金原ひとみ"],
  ["イン・ザ・メガチャーチ", "朝井リョウ"],
  ["正欲", "朝井リョウ"],
  ["スター", "朝井リョウ"],
  ["生殖記", "朝井リョウ"],
  ["ランチユーインザスカイ", "伊藤丸"],
  ["オーダーメイド殺人倶楽部", "辻村深月"],
  ["名前探しの放課後", "辻村深月"],
  ["汚れた手を、そこで拭かない", "芦沢央"],
  ["光のとこにいてね", "一穂ミチ"],
  ["わたしの美しい庭", "凪良ゆう"],
  ["滅びの前のシャングリラ", "凪良ゆう"],
  ["母という呪縛 娘という牢獄", "齋藤彩"],
  ["乳と卵", "川上未映子"],
  ["電波青年", "安田佳澄"],
  ["フールナイト", "安田佳澄"],
  ["左ききのエレン", "かっぴー"],
  ["閻魔堂沙羅の推理奇譚", "木元哉多"],
  ["ヌードモデル", "山口つばさ"],
  ["流浪の月", "凪良ゆう"],
  ["傲慢と善良", "辻村深月"],
  ["涼宮ハルヒの憂鬱", "谷川流"],
  ["タコピーの原罪", "タイザン5"],
  ["高校事変", "松岡圭祐"],
  ["JK", "松岡圭祐"],
  ["悲鳴伝", "西尾維新"],
  ["化物語", "西尾維新"],
  ["十二大戦", "西尾維新"],
  ["クビキリサイクル", "西尾維新"],
  ["暗号学園のいろは", "西尾維新"],
  ["スフィアの死天使", "知念実希人"],
  ["新本格魔法少女りすか", "西尾維新"],
  ["ウェルテルタウンでやすらかに", "西尾維新"],
  ["掟上今日子の備忘録", "西尾維新"],
  ["レゾンデートル", "知念実希人"],
  ["硝子の塔の殺人", "知念実希人"],
  ["優しい死神の飼い方", "知念実希人"],
  ["ムゲンのi", "知念実希人"],
  ["東京最低最悪最高！", "鳥トマト"],
  ["アッコちゃんは世界一", "鳥トマト"],
  ["2月に殺して桜に埋める", "鳥トマト"],
];
